branches:
  - main
tagFormat: ${version}
plugins:
  - [
      "@semantic-release/commit-analyzer",
      {
        preset: "conventionalcommits",
        releaseRules:
          [
            { type: "feat", release: "patch" },
            { type: "impr", release: "patch" },
            { type: "refactor", release: "patch" },
            { type: "perf", release: "patch" },
            { type: "fix", release: "patch" },
            { type: "ci", release: "patch" },
            { type: "docs", release: "patch" },
            { type: "chore", release: "patch" },
            { type: "style", release: "patch" },
            { type: "test", release: "patch" },
            { type: "build", release: "patch" },
          ],
      },
    ]
  - [
      "@semantic-release/release-notes-generator",
      {
        preset: "conventionalcommits",
        presetConfig:
          {
            types:
              [
                { type: "feat", section: "✨ Features" },
                { type: "impr", section: "🚀 Improvements" },
                { type: "refactor", section: "♻️ Improvements" },
                { type: "perf", section: "⚡️ Improvements" },
                { type: "fix", section: "🐛 Bug Fixes" },
                { type: "ci", section: "👷 CI" },
                { type: "docs", section: "📚 Documentation" },
                { type: "chore", section: "🔧 Miscellaneous" },
                { type: "style", section: "🎨 Miscellaneous" },
                { type: "test", section: "✅ Miscellaneous" },
                { type: "build", section: "📦 Miscellaneous" },
              ],
          },
      },
    ]
  - ["@semantic-release/changelog", { "changelogFile": "CHANGELOG.md" }]
  - [
      "@semantic-release/exec",
      {
        "prepareCmd": 'sed -i ''s/^version = .*$/version = "${nextRelease.version}"/'' Cargo.toml && cargo check',
      },
    ]
  - "@semantic-release/github"
  - [
      "@semantic-release/git",
      { "assets": ["CHANGELOG.md", "Cargo.lock", "Cargo.toml"] },
    ]
repositoryUrl: "https://github.com/edenreich/inference-gateway-rust-sdk"
