name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REGISTRY: crates.io

jobs:
  github_release:
    name: GitHub Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install semantic release and plugins
        run: |
          npm install -g semantic-release@v24.2.1 \
            conventional-changelog-cli \
            conventional-changelog-conventionalcommits \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github

      - name: Create a release if needed
        id: semantic
        run: |
          dry_run_output=$(semantic-release --dry-run 2>&1 || true)
          echo "Dry run output: $dry_run_output"

          # Check if there are no changes
          if $(echo "$dry_run_output" | grep -q "no new version is released"); then
            echo "No new release needed"
            echo "new_release_published=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "new_release_version=$(echo $dry_run_output | grep -i 'published release' | awk '{print $8}')" >> $GITHUB_OUTPUT
          semantic-release
          echo "new_release_published=true" >> $GITHUB_OUTPUT
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Output
        run: |
          echo "New Release Version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "New Release Published: ${{ steps.semantic.outputs.new_release_published }}"

  publish:
    needs: github_release
    runs-on: ubuntu-24.04
    if: needs.github_release.outputs.new_release_published == 'true'
    name: Publish
    steps:
      - name: Debug Condition
        run: |
          echo "new_release_published value: ${{ needs.github_release.outputs.new_release_published }}"
          echo "new_release_version value: ${{ needs.github_release.outputs.new_release_version }}"

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Update Cargo.toml version
        run: |
          echo "Updating to version ${{ needs.github_release.outputs.new_release_version }}"
          sed -i "s/^version = .*/version = \"${{ needs.github_release.outputs.new_release_version }}\"/" Cargo.toml

      - name: Build
        run: cargo build --verbose --release

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
